[project]
name = "cognee-community-retrievers"
version = "0.0.1"
description = "Package with custom cognee retrievers"
#readme = "README.md"
requires-python = ">=3.11,<=3.13"
dependencies = [
    "cognee>=0.4.0",
    "aenum>=3.1.16"
]