[project]
name = "cognee-community-tasks"
version = "0.0.1"
description = "Package with custom cognee tasks"
#readme = "README.md"
requires-python = ">=3.11,<=3.13"
dependencies = [
    "cognee>=0.4.0",
]