[project]
name = "cognee-community-vector-adapter-pinecone"
version = "0.1.0"
description = "Pinecone vector database adapter for cognee"
readme = "README.md"
requires-python = ">=3.11,<=3.13"
dependencies = [
    "pinecone>=3.0.0",
    "cognee==0.5.1",
    "starlette>=0.48.0",
    "instructor>=1.11"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
  "/dist",
  "/.venv",
]
