[project]
name = "cognee-community-tasks-codify"
version = "0.1.2"
description = "Package containing custom cognee tasks for the codify pipeline"
requires-python = ">=3.11,<=3.13"
dependencies = [
    "cognee==0.5.2",
]