[project]
name = "cognee-community-pipelines"
version = "0.0.1"
description = "Package with custom cognee pipelines"
#readme = "README.md"
requires-python = ">=3.11,<=3.13"
dependencies = [
    "cognee>=0.3.9",
    "fastembed<=0.6.0 ; python_version < '3.13'",
    "transformers>=4.46.3,<5",
    "tree-sitter>=0.24.0,<0.25",
    "tree-sitter-python>=0.23.6,<0.24",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
  "/dist",
  "/.venv",
]