[project]
name = "cognee-community-vector-adapter-weaviate"
version = "0.1.0"
description = "Weaviate vector database adapter for cognee"
readme = "README.md"
requires-python = ">=3.11,<=3.13"
dependencies = [
    "weaviate-client>=4.9.6,<5.0.0",
    "cognee==0.5.2",
    "starlette>=0.48.0",
    "instructor>=1.11"
] 